# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Snipper
                                 A QGIS plugin
 Ermöglicht einen spezifischen Bereich auszuwählen im richtigen Massstab.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-10
        copyright            : (C) 2025 by Genc Haxhija/ Liam Diener
        email                : genc.haxhija@stud.hslu.ch
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Snipper class from file Snipper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DC_Programm import Snipper
    return Snipper(iface)
